# Render Blueprint for Django Deployment
services:
  - type: web
    name: personal-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn portfolio_site.wsgi
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "<your-render-domain>"
