# Generated by Django 5.2.4 on 2025-09-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_contact_message_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='pdf',
            field=models.FileField(blank=True, help_text='Upload certificate as PDF', null=True, upload_to='certificates/'),
        ),
    ]
