# Generated by Django 5.2.4 on 2025-09-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_certificate_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('data', 'Data Analysis'), ('web', 'Web Development'), ('ml', 'Machine Learning')], default='web', max_length=20),
        ),
    ]
