# Generated by Django 5.2.4 on 2025-09-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Upload a PNG signature image.', null=True, upload_to='profile/signature/'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='signature_pdf',
            field=models.FileField(blank=True, help_text='Upload a PDF signature.', null=True, upload_to='profile/signature/'),
        ),
    ]
