# Generated by Django 5.2.6 on 2025-09-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_personalinfo_signature_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='certificate',
            name='order',
            field=models.IntegerField(default=0, help_text='Order for manual arrangement'),
        ),
    ]
